site_name: Customer 360 CoPilot Demo
site_url: https://github.com/dmccrearytg/c360
site_description: 'Resources for teaching classes TigerGraph CoPilot using Customer 360 model.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccrearytg.github.io/360'
repo_url: 'https://github.com/dmccrearytg/360'
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Graph Schema: graph-schema.md
  - Concepts:
    - Introduction: concepts/index.md
    - Personas: concepts/personas.md
    - Product Manager Questions: concepts/product-manager-questions.md
  - Contact: contact.md
  - References: references.md

# edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/tg-logo-small.png
  favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
# extra:
#  analytics:
#    provider: google
#    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-BBR7MPK96Z